import "./globals.css";
import Header from "@/components/Header";

export const metadata = {
  title: "Backengine Starter",
  description: "Generated by Backengine",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-background">
        <main className="min-h-screen flex flex-col items-center max-w-4xl mx-auto">
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
