import "./globals.css";
import Header from "@/components/Header";
import { ThemeProvider } from "@/components/theme-provider";

export const metadata = {
  title: "Backengine Starter",
  description: "Generated by Backengine",
};

export const dynamic = "force-dynamic";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-background">
        <ThemeProvider attribute="class" defaultTheme="light">
          <main className="min-h-screen flex flex-col max-w-7xl mx-auto">
            <Header />
            <div className="flex-1 border w-full flex rounded-lg bg-background shadow mb-24">
              {children}
            </div>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
