import BackengineLogo from "@/components/BackengineLogo";
import NextJsLogo from "@/components/NextJsLogo";
import SupabaseLogo from "@/components/SupabaseLogo";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";
import Link from "next/link";

export const dynamic = "force-dynamic";

export default async function Index() {
  const supabase = createServerComponentClient({ cookies });

  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <div className="w-full flex flex-col items-center justify-center flex-1">
      <div className="animate-in flex flex-col gap-14 opacity-0 max-w-4xl px-3 py-16 lg:py-24 text-foreground">
        <div className="flex flex-col items-center mb-4 lg:mb-12">
          <div className="flex gap-8 justify-center items-center">
            <BackengineLogo />
            <span className="border-l rotate-45 h-6" />
            <Link href="https://supabase.com/" target="_blank">
              <SupabaseLogo />
            </Link>
            <span className="border-l rotate-45 h-6" />
            <NextJsLogo />
          </div>
          <h1 className="sr-only">Supabase and Next.js Starter Template</h1>
          <p className="text-3xl lg:text-4xl !leading-tight mx-auto max-w-xl text-center my-12">
            The fastest way to start building apps with{" "}
            <strong>Backengine</strong>, <strong>Supabase</strong> and{" "}
            <strong>Next.js</strong>
          </p>
          {user && (
            <>
              <Link
                href="/project"
                className="bg-foreground py-3 px-6 rounded-lg text-sm text-background"
              >
                Get Started
              </Link>
            </>
          )}
          {!user && (
            <>
              <p className="mb-12">
                Login below to access the generated admin page for your project.
              </p>
              <Link
                href="/login"
                className="bg-foreground py-3 px-6 rounded-lg text-sm text-background"
              >
                Login
              </Link>
            </>
          )}
        </div>
        <div className="flex justify-center text-center text-xs">
          <p>
            Generated by{" "}
            <Link
              href="https://backengine.dev/"
              target="_blank"
              className="font-bold italic"
            >
              Backengine
            </Link>
          </p>
        </div>
      </div>
    </div>
  );
}
